# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import split_pb2 as split__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in split_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SplitLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForwardPass = channel.unary_unary(
                '/splitfed.SplitLearning/ForwardPass',
                request_serializer=split__pb2.ForwardRequest.SerializeToString,
                response_deserializer=split__pb2.ForwardReply.FromString,
                _registered_method=True)
        self.Inference = channel.unary_unary(
                '/splitfed.SplitLearning/Inference',
                request_serializer=split__pb2.InferenceRequest.SerializeToString,
                response_deserializer=split__pb2.InferenceReply.FromString,
                _registered_method=True)


class SplitLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ForwardPass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForwardPass': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardPass,
                    request_deserializer=split__pb2.ForwardRequest.FromString,
                    response_serializer=split__pb2.ForwardReply.SerializeToString,
            ),
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=split__pb2.InferenceRequest.FromString,
                    response_serializer=split__pb2.InferenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitfed.SplitLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitfed.SplitLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SplitLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ForwardPass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitfed.SplitLearning/ForwardPass',
            split__pb2.ForwardRequest.SerializeToString,
            split__pb2.ForwardReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitfed.SplitLearning/Inference',
            split__pb2.InferenceRequest.SerializeToString,
            split__pb2.InferenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
