# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: splitfed/grpc/split.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19splitfed/grpc/split.proto\x12\x08splitfed\"\xc4\x01\n\x0e\x46orwardRequest\x12\x18\n\x10\x61\x63tivation_bytes\x18\x01 \x01(\x0c\x12\x18\n\x10\x61\x63tivation_shape\x18\x02 \x03(\x05\x12\x1c\n\x14\x61ttention_mask_bytes\x18\x03 \x01(\x0c\x12\x1c\n\x14\x61ttention_mask_shape\x18\x04 \x03(\x05\x12\x0e\n\x06labels\x18\x05 \x03(\x05\x12\x11\n\tclient_id\x18\x06 \x01(\x05\x12\r\n\x05round\x18\x07 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x08 \x01(\x05\"r\n\x0c\x46orwardReply\x12\x1a\n\x12grad_smashed_bytes\x18\x01 \x01(\x0c\x12\x12\n\ngrad_shape\x18\x02 \x03(\x05\x12\x0e\n\x06logits\x18\x03 \x03(\x02\x12\x14\n\x0clogits_shape\x18\x04 \x03(\x05\x12\x0c\n\x04loss\x18\x05 \x01(\x02\"|\n\x10InferenceRequest\x12\x12\n\nactivation\x18\x01 \x03(\x02\x12\x18\n\x10\x61\x63tivation_shape\x18\x02 \x03(\x05\x12\x1c\n\x14\x61ttention_mask_bytes\x18\x03 \x01(\x0c\x12\x1c\n\x14\x61ttention_mask_shape\x18\x04 \x03(\x05\"6\n\x0eInferenceReply\x12\x0e\n\x06logits\x18\x01 \x03(\x02\x12\x14\n\x0clogits_shape\x18\x02 \x03(\x05\x32\x93\x01\n\rSplitLearning\x12?\n\x0b\x46orwardPass\x12\x18.splitfed.ForwardRequest\x1a\x16.splitfed.ForwardReply\x12\x41\n\tInference\x12\x1a.splitfed.InferenceRequest\x1a\x18.splitfed.InferenceReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'splitfed.grpc.split_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FORWARDREQUEST']._serialized_start=40
  _globals['_FORWARDREQUEST']._serialized_end=236
  _globals['_FORWARDREPLY']._serialized_start=238
  _globals['_FORWARDREPLY']._serialized_end=352
  _globals['_INFERENCEREQUEST']._serialized_start=354
  _globals['_INFERENCEREQUEST']._serialized_end=478
  _globals['_INFERENCEREPLY']._serialized_start=480
  _globals['_INFERENCEREPLY']._serialized_end=534
  _globals['_SPLITLEARNING']._serialized_start=537
  _globals['_SPLITLEARNING']._serialized_end=684
# @@protoc_insertion_point(module_scope)
