# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from splitfed.grpc import split_pb2 as splitfed_dot_grpc_dot_split__pb2


class SplitLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForwardPass = channel.unary_unary(
                '/splitfed.SplitLearning/ForwardPass',
                request_serializer=splitfed_dot_grpc_dot_split__pb2.ForwardRequest.SerializeToString,
                response_deserializer=splitfed_dot_grpc_dot_split__pb2.ForwardReply.FromString,
                )
        self.Inference = channel.unary_unary(
                '/splitfed.SplitLearning/Inference',
                request_serializer=splitfed_dot_grpc_dot_split__pb2.InferenceRequest.SerializeToString,
                response_deserializer=splitfed_dot_grpc_dot_split__pb2.InferenceReply.FromString,
                )


class SplitLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ForwardPass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForwardPass': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardPass,
                    request_deserializer=splitfed_dot_grpc_dot_split__pb2.ForwardRequest.FromString,
                    response_serializer=splitfed_dot_grpc_dot_split__pb2.ForwardReply.SerializeToString,
            ),
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=splitfed_dot_grpc_dot_split__pb2.InferenceRequest.FromString,
                    response_serializer=splitfed_dot_grpc_dot_split__pb2.InferenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitfed.SplitLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SplitLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ForwardPass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splitfed.SplitLearning/ForwardPass',
            splitfed_dot_grpc_dot_split__pb2.ForwardRequest.SerializeToString,
            splitfed_dot_grpc_dot_split__pb2.ForwardReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splitfed.SplitLearning/Inference',
            splitfed_dot_grpc_dot_split__pb2.InferenceRequest.SerializeToString,
            splitfed_dot_grpc_dot_split__pb2.InferenceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
