# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_generated.split_pb2 as split__pb2

class SplitLearningServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendActivations = channel.unary_unary(
                '/split.SplitLearningService/SendActivations',
                request_serializer=split__pb2.ActivationRequest.SerializeToString,
                response_deserializer=split__pb2.GradientResponse.FromString,
                )


class SplitLearningServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendActivations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendActivations': grpc.unary_unary_rpc_method_handler(
                    servicer.SendActivations,
                    request_deserializer=split__pb2.ActivationRequest.FromString,
                    response_serializer=split__pb2.GradientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'split.SplitLearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SplitLearningService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendActivations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/split.SplitLearningService/SendActivations',
            split__pb2.ActivationRequest.SerializeToString,
            split__pb2.GradientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
