# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: split.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsplit.proto\x12\x05split\"s\n\x11\x41\x63tivationRequest\x12\x13\n\x0b\x61\x63tivations\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x16\n\x0e\x61ttention_mask\x18\x03 \x03(\x02\x12\x12\n\nmask_shape\x18\x04 \x03(\x05\x12\x0e\n\x06labels\x18\x05 \x03(\x05\"T\n\x10GradientResponse\x12\x11\n\tgradients\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x02\x32\\\n\x14SplitLearningService\x12\x44\n\x0fSendActivations\x12\x18.split.ActivationRequest\x1a\x17.split.GradientResponseb\x06proto3')



_ACTIVATIONREQUEST = DESCRIPTOR.message_types_by_name['ActivationRequest']
_GRADIENTRESPONSE = DESCRIPTOR.message_types_by_name['GradientResponse']
ActivationRequest = _reflection.GeneratedProtocolMessageType('ActivationRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATIONREQUEST,
  '__module__' : 'split_pb2'
  # @@protoc_insertion_point(class_scope:split.ActivationRequest)
  })
_sym_db.RegisterMessage(ActivationRequest)

GradientResponse = _reflection.GeneratedProtocolMessageType('GradientResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRADIENTRESPONSE,
  '__module__' : 'split_pb2'
  # @@protoc_insertion_point(class_scope:split.GradientResponse)
  })
_sym_db.RegisterMessage(GradientResponse)

_SPLITLEARNINGSERVICE = DESCRIPTOR.services_by_name['SplitLearningService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVATIONREQUEST._serialized_start=22
  _ACTIVATIONREQUEST._serialized_end=137
  _GRADIENTRESPONSE._serialized_start=139
  _GRADIENTRESPONSE._serialized_end=223
  _SPLITLEARNINGSERVICE._serialized_start=225
  _SPLITLEARNINGSERVICE._serialized_end=317
# @@protoc_insertion_point(module_scope)
